{% set registry_url = salt['pillar.get']('docker_registry_url','') %}
{% set monitoring_version = salt['pillar.get']('monitoring:version:opg_docker_monitoring','latest') %}

dockbeat-client:
  image: {{ registry_url }}/opguk/dockbeat-client:{{monitoring_version}}
  log_driver: syslog
  env_file:
{%  set env_files = [] -%}
{%-  if salt['pillar.get']('services:dockbeat-client') is defined -%}
{%-    for env_name in salt['pillar.get']('services:dockbeat-client:env_files') -%}
{%-      do env_files.append(env_name) -%}
{%-    endfor -%}
{%-  endif %}
{%-  set output = [] -%}
{%-  for env_file in env_files -%}
{%-    if env_file not in output -%}
{{ '    - ./' +  env_file + '.env'}}
{%      do output.append(env_file) -%}
{%-    endif -%}
{%- endfor -%}
