{% from "monitoring/map.jinja" import monitoring with context %}

sensuclient:
  image: registry.service.dsd.io/opguk/sensu-client:{{monitoring.version.opg_docker_monitoring}}
  log_driver: syslog
  ports:
    - 3030:3030
  env_file:
    - ./sensuclient.env

{% for service in salt['pillar.get']('services:monitoring-client') %}
{% if 'env' in pillar['monitoring']['client'][service]%}
{% if service|string() not 'sensuclient' %}
    - ./{{service}}.env
{% endif %}
{% endif %}
{% endfor %}

# {{ monitoring.client }}