{% from "monitoring/map.jinja" import monitoring with context %}

sensuclient:
  image: registry.service.dsd.io/opguk/sensu-client:{{monitoring.version.opg_docker_monitoring}}
  log_driver: syslog
  ports:
    - 3030:3030
  env_file:
{% for env_name in salt['pillar.get']('services:monitoring-client:env_files') -%}
    - ./{{env_name}}.env
{% endfor %}
