#!/bin/sh

set -e

dbpath=$1
admin_password=$2

conf_file=/etc/mongod.conf

service_name="mongod"

hard_stop_mongod() {
  if !( pidof /usr/bin/mongod >/dev/null ); then
    return
  fi
  if stop mongod; then
    sleep 2
  fi
  if ( pidof /usr/bin/mongod >/dev/null ); then
    killall mongod
  else
    return
  fi
  sleep 2
  if ( pidof /usr/bin/mongod >/dev/null ); then
    killall -9 /usr/bin/mongod
  fi
}

check_admin_is_configured() {
  if ( mongo admin --eval 'printjson(db.serverStatus())' | grep -q version ); then
    # can get version without auth. No admin.
    return 1
  else
    return 0
  fi
}

if [ ! -d $dbpath ]; then
  echo "Mongo dbpath '${dbpath}' does not exist. Exiting"
  exit 1
fi

if [ -f "${dbpath}/DB_IS_CONFIGURED" ]; then
  echo "${dbpath}/DB_IS_CONFIGURED exists. Nothing to do!"
  exit 0
fi

hard_stop_mongod
sudo -u mongodb /usr/bin/mongod --dbpath ${dbpath} --fork --syslog --storageEngine wiredTiger
sleep 2

if check_admin_is_configured; then
  echo "DB admin is already present"
else
  mongo admin --eval "db.createUser({user: 'admin', pwd: '${admin_password}', roles: [ 'root', 'userAdminAnyDatabase' ]});"
fi

killall /usr/bin/mongod
sleep 2

touch ${dbpath}/DB_IS_CONFIGURED
